version: "3"
services:
  frontend:
    build: ./web
    environment:
      - REACT_APP_API_URL=http://127.0.0.1

  backend:
    build: .
    environment:
      - DB_HOST=db
      - DB_NAME=vankyle
      - DB_USER=postgres
      - DB_PASS=postgres
      - BASE_URL=http://127.0.0.1
    depends_on:
      - db

  reserve-proxy:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vankyle