version: "3"
services:
  web:
    build: .
    environment:
        - DB_HOST=db
        - DB_USER=postgres
        - DB_PASSWORD=postgres
        - DB_NAME=vankyle
        - BASE_URL=http://0.0.0.0:8080
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vankyle