spring.application.name=Vankyle ID

# Spring data JPA
spring.datasource.url=jdbc:${DATABASE_URL:postgresql://vankyle:randompassword@localhost:5432/vankyle_id?schema=public}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database=postgresql


## Email configuration
spring.mail.host=${EMAIL_HOST:smtp.mail.vankyle.com}
spring.mail.port=${EMAIL_PORT:465}
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
