package com.vankyle.id.service.validation;

import com.vankyle.id.service.security.User;

public interface ValidationService {
    /**
     * Validate the verification link code
     * <p>
     * The verification link code should contain the following parts:
     *     <ul>
     *         <li>username</li>
     *         <li>timestamp</li>
     *         <li>totp code</li>
     *         <li>purpose</li>
     *     </ul>
     * </p>
     *
     * @param code    Verification link code without decoded
     * @param purpose Verification link purpose
     * @return Verification with True success if the verification link code is valid
     */
    CodeVerification validateVerificationLinkCode(String code, String purpose);

    String generateVerificationLinkCode(User user, String purpose);

    /**
     * Generate the email confirmation code for the user
     * <p>
     * The email confirmation code is a TOTP code generated by the user's verification secret and
     * validate with a period of 60 minutes.
     * </p>
     *
     * @param user User to generate the email confirmation code
     * @return Email confirmation code
     */
    String generateEmailConfirmationCode(User user);

    CodeVerification validateEmailConfirmationCode(String code, User user);

    /**
     * Generate the phone confirmation code for the user
     * <p>
     *     The phone confirmation code is a TOTP code generated by the user's verification secret and
     *     validate with a period of 20 minutes.
 *     <p>
     * @param user User to generate the phone confirmation code
     * @return Phone confirmation code
     */
    String generatePhoneConfirmationCode(User user);

    CodeVerification validatePhoneConfirmationCode(String code, User user);

    String generate2FACode(User user);

    CodeVerification validate2FACode(String code, User user);

}
