# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Publish Release

on:
  release:
    types: [ created, unpublished ]

jobs:
  publish-gradle:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: release-api-package-${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          gradle-version: current

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: vankyle-id-api-${{ github.ref_name }}-artifacts
          path: build/libs/*.jar

      - name: Upload to Release
        run: |
            gh release upload ${{ github.ref_name }} build/libs/*.jar --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-docker-api:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    concurrency:
      group: release-api-docker-${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/vankyle-id-api

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/vankyle-id-nginx

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  publish-web:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ./web
    concurrency:
      group: release-web-package-${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
          cache-dependency-path: "web"

      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: vankyle-id-web-${{ github.ref_name }}-artifacts
          path: web/build

      - name: Upload to Release
        run: |
            zip Vankyle-ID-web-${{ github.ref_name }}.zip build
            gh release upload ${{ github.ref_name }} Vankyle-ID-web-${{ github.ref_name }}.zip --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-docker-web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    permissions:
      packages: write
    concurrency:
      group: release-web-docker-${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/vankyle-id-web

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.1.1
        with:
          context: web
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  publish-docker-nginx:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    concurrency:
      group: release-nginx-docker-${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

